### ISSUE TITLE
Lazy<IConnectionMultiplexer>

### ISSUE THREAD

**Issue by chemitaxis** [ziyasal/AspNetWebApi-OutputCache-Redis#1]
Hi, it would be better to change how IConnectionMultiplexer is instanced.

I think is better to change in RedisOutputCache.cs to :

` private readonly Lazy<IConnectionMultiplexer> _multiplexer;`

`_multiplexer = new Lazy<IConnectionMultiplexer>(() => ConnectionMultiplexer.Connect(_connectionSettings.ConnectionString));`

`private IDatabase DB => _multiplexer.Value.GetDatabase(_connectionSettings.Db);`

You can find more information here https://azure.microsoft.com/es-es/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/

What do you think? Thanks.

**Comment by bugthesystem** [comment]
Hi @chemitaxis Thank you, that makes sense.
